### ISSUE TITLE
Caught error undefined method `column_type=' for #<Google::Apis::AnalyticsV3::GaData::ColumnHeader:0x007ff45f2bb028>

### ISSUE THREAD

**Issue by swapnilchincholkar** [google/google-api-ruby-client#254]
I was using 0.8.6 & was successfully retriving json data using <code>client.execute(:api_method => @analytics.data.ga.get, :parameters => params)</code> & using that json data in own way. Now when migrated to 0.9.pre1, using code below I am facing error in column header. I want to get json data only. Below queries I am executing on server console.

Details are below

My code is:
<pre><code>
require 'google/apis'
require 'google/apis/analytics_v3'
require 'google/api_client/client_secrets'
client_secrets = Google::APIClient::ClientSecrets.load
auth_client = client.to_authorization
scope = 'https://www.googleapis.com/auth/analytics.readonly'
auth_client.update!(scope: scope)
</code></pre>
Now I am getting the url using auth_client.authorization_uri.to_s & pasting it in browser to get code.
<code><pre>
auth_client.code = code_from_browser
auth_client.fetch_access_token!
cl = Google::Apis::AnalyticsV3::AnalyticsService.new
cl.authorisation = auth_client
start_date = (Date.today - 7.days).strftime('%Y-%m-%d')
end_date = Date.today.strftime('%Y-%m-%d')
ids = 'ga:my id here' 
metrics = 'ga:percentNewSessions,ga:sessions'
dimensions = 'ga:date'
cl.get_ga_data(dimensions: dimensions, end_date: end_date, start_date: start_date, metrics: metrics, ids: ids)
</code></pre>

Here I am getting the error.
Below are the logs

<pre>
Sending HTTP get https://www.googleapis.com/analytics/v3/data/ga?dimensions=ga%3Adate&end-date=2015-07-12&ids=ga%3Amy-id-here&metrics=ga%3ApercentNewSessions%2Cga%3Asessions&start-date=2015-07-05

200

#Hurley::Response GET https://www.googleapis.com/analytics/v3/data/ga?dimensions=ga%3Adate&end-date=2015-07-12&ids=ga%3Amy-id-here&metrics=ga%3ApercentNewSessions%2Cga%3Asessions&start-date=2015-07-05 == 200 (1415 bytes) 4015ms
</pre>

& then I am getting error as 

<code><pre>
Caught error undefined method `column_type=' for #<Google::Apis::AnalyticsV3::GaData::ColumnHeader:0x007ff45f2bb028>
Error - #<NoMethodError: undefined method `column_type=' for #<Google::Apis::AnalyticsV3::GaData::ColumnHeader:0x007ff45f2bb028>>

NoMethodError: undefined method `column_type=' for #<Google::Apis::AnalyticsV3::GaData::ColumnHeader:0x007ff45f2bb028>
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:104:in `block in set'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:120:in `evaluate_option'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:103:in `set'
	from /my rvm path/gems/representable-2.2.3/lib/representable/populator.rb:27:in `call'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:85:in `read_fragment'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:64:in `block in uncompile_fragment'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:120:in `evaluate_option'
	from /my rvm path/gems/representable-2.2.3/lib/representable/binding.rb:63:in `uncompile_fragment'
	from /my rvm path/gems/representable-2.2.3/lib/representable/mapper.rb:77:in `uncompile_fragment'
	from /my rvm path/gems/representable-2.2.3/lib/representable/mapper.rb:38:in `deserialize_property'
	from /my rvm path/gems/representable-2.2.3/lib/representable/mapper.rb:18:in `block in deserialize'
	from /my rvm path/gems/representable-2.2.3/lib/representable/mapper.rb:17:in `each'
	from /my rvm path/gems/representable-2.2.3/lib/representable/mapper.rb:17:in `deserialize'
	from /my rvm path/gems/representable-2.2.3/lib/representable.rb:41:in `update_properties_from'
	from /my rvm path/gems/representable-2.2.3/lib/representable/hash.rb:31:in `from_hash'
	from /my rvm path/gems/representable-2.2.3/lib/representable/deserializer.rb:36:in `demarshal'
... 41 levels...
	from /my rvm path/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /my rvm path/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /my rvm path/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /my rvm path/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/SwapnilChincholkar/work/clickx/bin/rails:8:in `<top (required)>'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /my rvm path/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/SwapnilChincholkar/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/SwapnilChincholkar/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.0-preview1 :069 > 
</code></pre>

When debugging, I can see data is returned correctly when I have added print statement at  "lib/google/apis/core/api_command.rb" line no: 70 like 
<pre><code>
 69         def decode_response_body(content_type, body)
 70           p body.inspect
 71           return super unless response_representation
 72           return super if content_type.nil?
 73           return nil unless content_type.start_with?(JSON_CONTENT_TYPE)
 74           instance = response_class.new
 75           response_representation.new(instance).from_json(body, unwrap: response_class)
 76           instance
 77         end
</code></pre>

Am I missing any configuration OR I am using wrong method to get json data?

**Comment by sqrrrl** [comment]
You're using a broken ruby version. Looks like this is https://bugs.ruby-lang.org/issues/10259 which was fixed in release versions of 2.2.

I did  a quick test to confirm -- get the same error on 2.2.0-preview1, but not using 2.2.2.
